import { useState, useEffect } from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { getDatabase, get, ref, child } from 'firebase/database'
import Image from 'next/image'

export default function Login() {
    const [windowHeight, setWindowHeight] = useState(null)
    const router = useRouter()
    const [user, setUser] = useState(null)
    const db = getDatabase();

    //Window size
    useEffect(() => {
        const handleResize = () => {
            setWindowHeight(window.innerHeight)
        }

        handleResize()

        window.addEventListener('resize', handleResize)
        return () => window.removeEventListener('resize', handleResize)
    }, [])

    //Fetch data
    useEffect(() => {
        const fetchData = async () => {
            try {
                const snapshot = await get(child(ref(db), 'users/'))

                var users = []
                snapshot.forEach((childSnapshot) => {
                    if (childSnapshot.val().email === router.query.user) {
                        setUser(childSnapshot.val())
                        return
                    }
                })
            } catch (error) {

            }
        }
        fetchData()
    }, [db]);

    return (
        <>
            <Head>
                <title>Linktree</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="main_user" style={{ minHeight: windowHeight }}>
                {user ? (
                    <div className='main_user_profile'>
                        <Image
                            className='max-w-[80px]'
                            src={user.gender === 'male' ?
                                'https://ik.imagekit.io/ricardo5ro/Linktree/icons/user.png?updatedAt=1684087499218' :
                                'https://ik.imagekit.io/ricardo5ro/Linktree/icons/woman.png?updatedAt=1684161997979'}
                            width={500} height={500} alt='User photo'>
                        </Image>
                        <h3>@{user.userName}</h3>
                        {user.links.slice(1).map((link, indexLink) => (
                            <a key={indexLink} className={`user_link ${(indexLink % 2 === 0 ? 'bg-[#201e1e]' : 'bg-[#808080]')}`} href={link.url} target="_blank" rel="noopener noreferrer">{link.title}</a>
                        ))}
                    </div>
                ) : (
                    <h3>Not found</h3>
                )}
            </div>
        </>
    )
}