import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'

export default function Account() {
    const [windowHeight, setWindowHeight] = useState(null)

    useEffect(() => {
        const handleResize = () => {
          setWindowHeight(window.innerHeight)
        }
    
        handleResize()
        
        window.addEventListener('resize', handleResize)
        return () => window.removeEventListener('resize', handleResize)
      }, [])

    const newLocal = 'account_profileImg'
    return (
        <>
            <Head>
                <title>Linktree</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className='main_account' style={{ minHeight: windowHeight }}>
                <div className='phone_model'>
                    <Image src='https://ik.imagekit.io/ricardo5ro/Linktree/icons/user.png?updatedAt=1684087499218' width={500} height={500} alt='User photo' className={newLocal}></Image>
                    <span className='username'>@ricardo5ro</span>
                    <div className='account_link'>
                        <Image src='https://ik.imagekit.io/ricardo5ro/Linktree/icons/instagram.png?updatedAt=1684088942361' width={500} height={500} alt='Social icon'></Image>
                        <span>Instragram</span>
                    </div>
                </div>
                <div className='account_info'>
                    <form>
                        <input></input>
                        <input></input>
                        <input></input>
                        <input></input>
                    </form>
                </div>
            </div>
        </>
    )
}