import Head from 'next/head'
import { useState, useEffect } from 'react'
import { useRouter } from "next/router";
import Image from 'next/image';

export default function Discover() {
    const [windowHeight, setWindowHeight] = useState(null)
    const router = useRouter();
    const searchQueryTemp = router.query.searchInfo;

    //Window size
    useEffect(() => {
        const handleResize = () => {
            setWindowHeight(window.innerHeight)
        }

        handleResize()

        window.addEventListener('resize', handleResize)
        return () => window.removeEventListener('resize', handleResize)
    }, [])

    return (
        <>
            <Head>
                <title>Linktree</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className='discover_main'>
                <div className='discover_profile bg-[#f372728f]' style={{ minHeight: windowHeight }}>
                    <Image className='max-w-[70px]' src='https://ik.imagekit.io/ricardo5ro/Linktree/icons/user.png?updatedAt=1684087499218' width={500} height={500} alt='User photo'></Image>
                    <h3>@ricardo5ro</h3>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                </div>


                <div className='discover_profile bg-[var(--background-grey)]' style={{ minHeight: windowHeight }}>
                    <Image className='max-w-[70px]' src='https://ik.imagekit.io/ricardo5ro/Linktree/icons/user.png?updatedAt=1684087499218' width={500} height={500} alt='User photo'></Image>
                    <h3>@ricardo5ro</h3>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                </div>


                <div className='discover_profile bg-[#f372728f]' style={{ minHeight: windowHeight }}>
                    <Image className='max-w-[70px]' src='https://ik.imagekit.io/ricardo5ro/Linktree/icons/user.png?updatedAt=1684087499218' width={500} height={500} alt='User photo'></Image>
                    <h3>@ricardo5ro</h3>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_odd' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                </div>


                <div className='discover_profile bg-[var(--background-grey)]' style={{ minHeight: windowHeight }}>
                    <Image className='max-w-[70px]' src='https://ik.imagekit.io/ricardo5ro/Linktree/icons/user.png?updatedAt=1684087499218' width={500} height={500} alt='User photo'></Image>
                    <h3>@ricardo5ro</h3>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                    <a className='discover_link discover_link_even' href='https://www.instagram.com/cristiano/' target="_blank" rel="noopener noreferrer">Instagram</a>
                </div>
            </div>
        </>
    )
}