import { useState, useEffect } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from "next/router";
import Head from 'next/head'

import firebase_app from '../../firebase-config'
import { createUserWithEmailAndPassword, getAuth } from "firebase/auth";

const auth = getAuth(firebase_app);


export default function Signup() {
    const [windowHeight, setWindowHeight] = useState(null)
    const emailTemp = useRouter().query.emailTemp;
    const [inputValue, setInputValue] = useState(emailTemp);
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')

    useEffect(() => {
        const handleResize = () => {
            setWindowHeight(window.innerHeight)
        }

        handleResize()

        window.addEventListener('resize', handleResize)
        return () => window.removeEventListener('resize', handleResize)
    }, [])

    const handleInputChange = (e) => {
        setInputValue(e.target.value);
        setEmail(e.target.value)
    };

    const handleForm = async (event) => {
        event.preventDefault()

        const { result, error } = await signUp(email, password);

        if (error) {
            return console.log(error)
        }

        // else successful
        console.log(result)
        //return router.push("/admin")
    }

    return (
        <>
            <Head>
                <title>Linktree</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="main_signup_login" style={{ minHeight: windowHeight }}>
                <div className="signup_login">
                    <form className='form' onSubmit={handleForm}>
                        <h1>Create your account</h1>
                        <h3>One link, infinite connections.</h3>
                        <input placeholder='Email' value={inputValue} onChange={handleInputChange} name="email" id="email" required type="email" autoComplete='off'></input>
                        <input placeholder='Password' onChange={(e) => setPassword(e.target.value)} name="password" id="password" required type="password" autoComplete='off'></input>
                        <input placeholder='Confirm Password' autoComplete='off' required type="password"></input>
                        <button id='signup_btn' type="submit">Sign Up</button>
                        <p>Already have an account? <Link href='/login'>Log In</Link></p>
                    </form>
                </div>
                <div className="banner">
                    <Image src='https://ik.imagekit.io/ricardo5ro/Linktree/general/signup.jpg?updatedAt=1683627571722' alt='Side banner' width={windowHeight / 1.5} height={windowHeight * 1}></Image>
                </div>
            </div>
        </>
    )
}

async function signUp(email, password) {
    let result = null,
        error = null;
    try {
        result = await createUserWithEmailAndPassword(auth, email, password);
    } catch (e) {
        error = e;
    }

    return { result, error };
}